void function_throwing_exception() { throw int(42); }
